IBDEINIT ; ; 04-JAN-2011
 ;;3.0;IB ENCOUNTER FORM IMP/EXP;;JAN 04, 2011
 ;
 K
DIF,DIFQ,DIFQR,DIFQN,DIK,DDF,DDT,DTO,D0,DLAYGO,DIC,DIDUZ,DIR,DA,DIFROM,D
FR,DTN,DIX,DZ,DIRUT,DTOUT,DUOUT
 S DIOVRD=3D1,U=3D"^",DIFQ=3D0,DIFROM=3D"3.0" W !,"This version (#3.0) =
of
'IBDEINIT' was created on 04-JAN-2011"
 W !?9,"(at TEST.MANCHESTER.MED.VA.GOV, by VA FileMan V.22.0)",!
 I $D(^DD("VERSION")),^("VERSION")'<22 G GO
 ;W !,"FIRST, I'LL FRESHEN UP YOUR VA FILEMAN...." D N^DINIT
 I ^DD("VERSION")<22 W !,"but I need version 22 of the VA FileMan!" G Q
GO ;
 W !,"I HAVE TO RUN AN ENVIRONMENT CHECK ROUTINE." D PKG,^IBDEPRE
Q:'$D(DIFQ)  D NOW^%DTC S DIFROM("PRE")=3D%
EN ; ENTER HERE TO BYPASS THE PRE-INIT PROGRAM
 S DIFQ=3D0 K DIRUT,DTOUT,DUOUT
 F DIFRIR=3D1:1:1 S DIFRRTN=3D"^IBDEINI"_$E("5",DIFRIR) D @DIFRRTN
 W:1 !,"I AM GOING TO SET UP THE FOLLOWING FILES:" F I=3D1:2:28 S
DIF(I)=3D^UTILITY("DIF",$J,I) D 1 G Q:DIFQ!$D(DIRUT) K DIF(I)
 S DIFROM=3D"3.0" D PKG:'$D(DIFROM(0)),^IBDEINI1 G Q:'$D(DIFQ) S
DIK(0)=3D"AB"
 F DIF=3D1:2:28 S
%=3D^UTILITY("DIF",$J,DIF),DIK=3D$P(%,";",5),N=3D$P(%,";",3),D=3D$P(%,";"=
,4)_U_N
D D K DIFQ(N)
 K DIFQR D ^IBDEINI2,^IBDEINI3
 L  S DUZ=3DDIDUZ W:1 !,"NO"_$P("TE THAT FILE",U,DSEC)_" SECURITY-CODE
PROTECTION HAS BEEN MADE"
 D ^IBDEPT,NOW^%DTC S DIFROM("INIT")=3D%
 I DIFROM F DIF=3D1:2:28 S %=3D^UTILITY("DIF",$J,DIF),N=3D+$P(%,";",3) I
N,$P(%,";",8)=3D"y" S ^DD(N,0,"VR")=3DDIFROM
 I DIFROM(0)>0 F %=3D"PRE","INI","INIT" S:$D(DIFROM(%))
