IBDEINI1 ; ; 04-JAN-2011
 ;;3.0;IB ENCOUNTER FORM IMP/EXP;;JAN 04, 2011
 ; LOADS AND INDEXES DD'S
 ;
 K DIF,DIK,D,DDF,DDT,DTO,D0,DLAYGO,DIC,DIDUZ,DIR,DA,DFR,DTN,DIX,DZ D
DT^DICRW S %=3D1,U=3D"^",DSEC=3D1
 S NO=3D$P("I 0^I $D(@X)#2,X[U",U,%) I %<1 K DIFQ Q
ASK I %=3D1,$D(DIFQ(0)) W !,"SHALL I WRITE OVER FILE SECURITY CODES" S =
%=3D2
D YN^DICN S DSEC=3D%=3D1 I %<1 K DIFQ Q
 Q:'$D(DIFQ)  S %=3D2 W !!,"ARE YOU SURE EVERYTHING'S OK" D YN^DICN I =
%-1
K DIFQ Q
 D ^IBDE2 D NOW^%DTC S DIFROM("INI")=3D%
 I $D(DIFKEP) F DIDIU=3D0:0 S DIDIU=3D$O(DIFKEP(DIDIU)) Q:DIDIU'>0  S
DIU=3DDIDIU,DIU(0)=3DDIFKEP(DIDIU) D EN^DIU2
 D DT^DICRW K ^UTILITY(U,$J),^UTILITY("DIK",$J) D WAIT^DICD
 S DN=3D"^IBDEI" F R=3D1:1:30 D @(DN_$$B36(R)) W "."
 F  S D=3D$O(^UTILITY(U,$J,"SBF","")) Q:D'>0  K:'DIFQ(D) ^(D) S
D=3D$O(^(D,"")) I D>0  K ^(D) D IX
DATA W "." S (D,DDF(1),DDT(0))=3D$O(^UTILITY(U,$J,0)) Q:D'>0
 I DIFQR(D) S
DTO=3D0,DMRG=3D1,DTO(0)=3D^(D),Z=3D^(D)_"0)",D0=3D^(D,0),@Z=3DD0,DFR(1)=3D=
"^UTILITY(U,
