YS43POST ;DALCIOFO/MJD-YS*5.01*43 POST ROUTINE ; 1/7/99
 ;;5.01;MENTAL HEALTH;**43**;Dec 30, 1994
SITE ;ENTER PRIMARY SITE NUMBER TO HL7 APLICATION
 S YSVS=$$PRIM^VASITE(DT) I $G(YSVS)'="" D
 .S YSVS=$$SITE^VASITE(DT,YSVS)
 .S PRIMARY=$P(YSVS,U,3)
 .Q:+PRIMARY'>0
 .S YSPP=$O(^HL(771,"B","YS GAF",0))
 .Q:+YSPP'>0
 .Q:'$D(^HL(771,YSPP,0))
 .S $P(^HL(771,YSPP,0),U,3)=PRIMARY
 K PRIMARY,YSPP,YSVS
 QUIT
